version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    funlen:
      lines: 140
      statements: 90
    gocritic:
      enabled-checks:
        - deferInLoop
    gosec:
      excludes:
        - G115
    gocognit:
      min-complexity: 80
    gocyclo:
      min-complexity: 50
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-same-issues: 25
  uniq-by-line: false

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
